name: Deploy Theme to cPanel via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Theme
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug Server Paths
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            pwd
            ls -la
            echo "Checking public_html..."
            ls -la public_html/
            echo "Checking themes dir..."
            ls -la public_html/wp-content/themes/buildlatam-theme/
